In [2]:
import numpy as np 

Creating array from list     

In [5]:
arr_1d =np.array([1, 2, 3, 4, 5])
print(arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:", arr_2d)

[1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


list vs numpy array


In [6]:
py_list = [1, 2, 3, 4, 5]
print("Python list multiplication:", py_list * 2)

np_array = np.array([1, 2, 3, 4, 5])
print("Numpy array multiplication:", np_array * 2)


import time
start = time.time()
py_list =[i*2 for i in range(1000000)]
print("Python list comprehension time:", time.time() - start)






Python list multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication: [ 2  4  6  8 10]
Python list comprehension time: 0.17054367065429688


In [12]:
zeros = np.zeros((3, 4))
print("zeros array:\n", zeros)

ones = np.ones((2, 3))
print("ones array:\n", ones)

full = np.full((2, 3), 7)
print("full array:\n", full)


random_array = np.random.rand(3, 4)
print("random array:\n", random_array)


sequence = np.arange(0, 12, 2)
print("arange sequence:", sequence)


zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7 7]
 [7 7 7]]
random array:
 [[0.89563389 0.34448052 0.64991069 0.81582499]
 [0.6002915  0.02163079 0.17985518 0.71869816]
 [0.70543203 0.43719731 0.66652363 0.69675185]]
arange sequence: [ 0  2  4  6  8 10]


Vector Matrix Tensor

In [ ]:
vector = np.array([1, 2, 3])
print("Vector:", vector)


matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)


tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)
# Numpy Basics: Creating and Manipulating Arrays
# Vector, Matrix, Tensor



Vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:", arr.shape)
print("Array dimensions:", arr.ndim)
print("Array data type:", arr.dtype)
print("Array size:", arr.size)
print("Array item size (in bytes):", arr.itemsize)
print("Array total bytes:", arr.nbytes)
print("Array type:", type(arr))
# Numpy Basics: Array Properties

Array shape: (2, 3)
Array dimensions: 2
Array data type: int64
Array size: 6
Array item size (in bytes): 8
Array total bytes: 48
Array type: <class 'numpy.ndarray'>


Array reshaping


In [ ]:
arr = np.arange(12)
print("Original array:", arr)

reshaped_arr = arr.reshape((3, 4))
print("Reshaped array (3x4):\n", reshaped_arr)

flattend = reshaped_arr.flatten()
print("Flattened array:", flattend)

raveled = reshaped_arr.ravel()
print("Raveled array:", raveled)



Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
#Transpose
transposed = reshaped_arr.T
print("Transposed array:\n", transposed)


Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
