Numpy Array operation

In [3]:
import numpy as np

In [4]:
arr = np .array([1, 2, 3, 4, 5 , 6, 7, 8, 9])
print("Bsic Slicing , arr[2:7]")
print("With Step" , arr[1:8:2])
print("Reverse Array" , arr[::-1])
print("Every Second Element" , arr[::2])
print("Last Three Elements" , arr[-3:])
print("All But Last Three Elements" , arr[:-3])
print("From Start to Index 5" , arr[:5])
print("Negative indexing" , arr[-5])

Bsic Slicing , arr[2:7]
With Step [2 4 6 8]
Reverse Array [9 8 7 6 5 4 3 2 1]
Every Second Element [1 3 5 7 9]
Last Three Elements [7 8 9]
All But Last Three Elements [1 2 3 4 5 6]
From Start to Index 5 [1 2 3 4 5]
Negative indexing 5


In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Specific element", arr_2d[1, 2])  # Element at row 1, column 2
print("Entire row", arr_2d[0, :])  # Entire first row
print("Entire column", arr_2d[:, 1])  # Entire second column

Specific element 6
Entire row [1 2 3]
Entire column [2 5 8]


Sorting

In [6]:
unsorted_arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
sorted_arr = np.sort(unsorted_arr)
print("Unsorted array:", unsorted_arr)
print("Sorted array:", sorted_arr)

arr_2d_unsorted = np.array([[3, 1, 2], [6, 4, 5], [9, 7, 8]])
print("Unsorted 2D array:\n", arr_2d_unsorted)
sorted_arr_2d = np.sort(arr_2d_unsorted, axis=1)  # Sort each row
print("Sorted 2D array by rows:\n", sorted_arr_2d)

Unsorted array: [3 1 4 1 5 9 2 6 5]
Sorted array: [1 1 2 3 4 5 5 6 9]
Unsorted 2D array:
 [[3 1 2]
 [6 4 5]
 [9 7 8]]
Sorted 2D array by rows:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


#filter


In [7]:
numbers = np.array([1, 2, 3, 4, 5 ,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers:", even_numbers)


Even numbers: [ 2  4  6  8 10]


In [8]:
numbers = np.array([1, 2, 3, 4, 5 ,6,7,8,9,10])
odd_mask = numbers % 2 != 0
odd_numbers = numbers[odd_mask]
print("Odd numbers:", odd_numbers)

Odd numbers: [1 3 5 7 9]


Filter with mask


In [9]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])


Numbers greater than 5: [ 6  7  8  9 10]


In [10]:
mask = numbers >9
print("Numbers greater than 9:", numbers[mask])

Numbers greater than 9: [10]


Fancy indexing vs np.where()

In [11]:
indices = [0, 2, 4]
print(numbers[indices])  # Output: [1 3 5]
#Fancy indexing vs np.where()


where_result = np.where(numbers > 5)
print("Indices of numbers greater than 5:", where_result[0])

[1 3 5]
Indices of numbers greater than 5: [5 6 7 8 9]


In [14]:
condition_array = np.where(numbers > 5, True, False)
print("Condition array (numbers > 5):", condition_array)

Condition array (numbers > 5): [False False False False False  True  True  True  True  True]


Adding and removing data

In [18]:
arr1 =np.array([1, 2, 3])
arr2 =np.array([4, 5, 6])   

combined = np.concatenate((arr1, arr2))
print(combined)  # Output: [5 7 9]


[1 2 3 4 5 6]


Array compatiblity


In [20]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Compatible shapes for addition " , a.shape == b.shape)

Compatible shapes for addition  True


In [ ]:
original = np.array([[1, 2] , [3,  4 ]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack([original, new_row])
print("Array after adding new row:\n", with_new_row)
print("Array compatibility")



Array after adding new row:
 [[1 2]
 [3 4]
 [5 6]]
Array compatibility
